spring.application.name=assistant

spring.data.mongodb.uri=mongodb://localhost:27017/college_assistant

# JWT properties
app.jwt.secret=YOUR_JWT_SECRET_HERE
app.jwt.expiration-ms=86400000

# Server port
server.port=8082

spring.data.mongodb.auto-index-creation=true

# Gemini API Key
app.gemini.api-key=YOUR_API_KEY_HERE
app.gemini.model=gemini-flash-latest
